# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription JLGimarino(86e3ec14-d6c8-40ee-94f0-91fbfe56153d)'
    subscriptionId: '86e3ec14-d6c8-40ee-94f0-91fbfe56153d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRMPipeline-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/acid387/JLG-repo/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName jlgpipe01'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'